### ISSUE TITLE
Setup the database

### ISSUE THREAD

**Issue by Leeoku** [Leeoku/pearish#5]

**Comment by Leeoku** [comment]
Team Data to try Mongo. @OmarMoghazy to delegate tasks

**Comment by OmarMoghazy** [comment]
I created a mongodb free cluster for our project.

Database connection key:
`mongodb+srv://SGP:<password>@stackedup-nr3iv.mongodb.net/<db_name>?retryWrites=true&w=majority`

Database name is "StackedUp" and it has one collection called "users". Every user is gonna have a document inside this collection. (Think of documents as rows in a table)

**Comment by OmarMoghazy** [comment]
I did the following to set up the database: 
1- Created an account on https://www.mongodb.com/cloud/atlas
2- Created a free cluster and chose to host it on AWS (You can choose either AWS, GCP or Microsoft Azure). I am not that is really gonna make any difference though :sweat_smile: 
3- Now I needed to create a user, so under the "Overview" tab I clicked the "connect" button. There is an option to create a user.
4- I created a user "SGP" with password "*********" (those are included inside the connection key if you take a look)
5- Next, you have to whitelist an IP address so that it can access the data base. If you enter the specific IP address "0.0.0.0" it allows anybody to access the database so that is what I did for testing purposes.
6- Now to create the actual database, I went to the collections tab and clicked on "Insert my own data" which then gives you the option to create a database and a collection inside it. 

To be clear: A database is like a group of tables, a collection is like a single table and a document is a row(entry) inside the table.
